### PR TITLE
Authentication mechanism

### PR DESCRIPTION
**Pull request by alexkefer**
Added the authentication module and testing it to connect to ContactUs if the authentication fails just to see how it all works to begin with, if works I already separated the portion we want hidden into a separate component to simplify the authorization process. This is a test PR. DO NOT MERGE!

### CODE REVIEW

**Comment by alexkefer** [comment]
Got it working to a point, I sent an email explaining the current situation I am at with it.

**Comment by WWU-MaxBronsema** [comment]
Slick. Mainly the config file got the additional routing information. It seems like the other commits are related to moving the text generator into it's own file. Hopefully the new token enabling makes this work.

**Comment by alexkefer** [comment]
Currently hides the homepage to not logged in users, reroutes them to the login page, then once logged in, routes them back to the working web app. Next is working on getting user data from the page in order to continue developing the database based on the user logged in on the personal statistics page. I need the account information in order to craft the database properly.

**Comment by davidengebretson** [comment]
You want a review and not a merge?

**Comment by davidengebretson** [comment]
Which account information are you referencing In the below sentence:
"I need the account information in order to craft the database properly."?

**Comment by alexkefer** [comment]
Hey David, I am still working on it though I added you as a reviewer so you
can see its progress in updates and so you can verify the login works on
your end and is accessible and understandable to use (It should be as it is
simply running you through the western portal as most other western
applications do). Technically it does work as a login mechanism but I am
continuing to iterate in order to prepare the personal data pages and
administration pages. So whilst it is at a point where with a quick update
to the Redirect URI it can be merged, I think with a couple more days I can
have it ready to be merged with feature sets ready for future iterations.

**Comment by davidengebretson** [comment]
Are you taking care of the Redirect URI, or is there something I can do to help with that?

**Comment by alexkefer** [comment]
I was going to put a ticket in after my class to have that added to the redirect uri. Basically just the link needs to be the same format but the base (pre slashes) needs to be updated to the non branch link. If you want to get that in you are welcome to do so.
Alex
________________________________

**Comment by davidengebretson** [comment]
I’ll let you take care of that. 😊

**Pull request merged**
